data:extend({
  { type = "fluid", name = "propene",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenChemicals__/graphics/icons/fluid/propene.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "hydrogen",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenChemicals__/graphics/icons/fluid/hydrogen.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "chlorine",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenChemicals__/graphics/icons/fluid/chlorine.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "hydrogen-chloride",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenChemicals__/graphics/icons/fluid/hydrogen-chloride.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "hydrochloric-acid",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenChemicals__/graphics/icons/fluid/hydrochloric-acid.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "ammonia",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenChemicals__/graphics/icons/fluid/ammonia.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "carbon-monoxide",
    default_temperature = 15,
    heat_capacity = "0KJ",
    base_color = {r=0.4, g=0, b=0.4},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    icon = "__CartmenChemicals__/graphics/icons/fluid/carbon-monoxide.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "a[fluid]-e[petroleum-gas]"
  },
  
  { type = "fluid", name = "sulfur-dioxide",
    default_temperature = 15,
	max_temperature = 15,
	heat_capacity = "0KJ",
	base_color = {r=0, g=0.7, b=0.2},
    flow_color = {r=0.5, g=0.5, b=0.5},
	icon = "__CartmenChemicals__/graphics/icons/fluid/sulfur-dioxide.png",
	pressure_to_speed_ratio = 0.4,
	flow_to_energy_ratio = 0.59,
  },
  
  { type = "fluid", name = "nitrogen",
    default_temperature = 15,
	max_temperature = 15,
	heat_capacity = "0KJ",
	base_color = {r=0, g=0.7, b=0.2},
    flow_color = {r=0.5, g=0.5, b=0.5},
	icon = "__CartmenChemicals__/graphics/icons/fluid/nitrogen.png",
	pressure_to_speed_ratio = 0.4,
	flow_to_energy_ratio = 0.59,
  },
})